import { SLICE_NAME } from '@config/type';

export const VALIDATE = SLICE_NAME.REGISTER + 'VALIDATE';
export const REGISTER = SLICE_NAME.REGISTER + 'REGISTER';
export const RESEND_OTP = SLICE_NAME.REGISTER + 'RESEND_OTP';
export const CONFIRM = SLICE_NAME.REGISTER + 'CONFIRM';
export const CHECK_CONTRACT = SLICE_NAME.REGISTER + 'CHECK_CONTRACT';
export const GET_PROVINCE = SLICE_NAME.REGISTER + 'GET_PROVINCE';
export const GET_CITY = SLICE_NAME.REGISTER + 'GET_CITY';
export const GET_POSTAL_CODE = SLICE_NAME.REGISTER + 'GET_POSTAL_CODE';
export const GET_CITY_WRAP = SLICE_NAME.REGISTER + 'GET_CITY_WRAP';
