export const icons = {
  send: require('./source/send.png'),
  back: require('./source/arrow-left.png'),
  bullet: require('./source/bullet.png'),
  close: require('./source/ic_close.png'),
  plus: require('./source/ic_plus.png'),
  home: require('./source/ic_home.png'),
  heart: require('./source/ic_heart.png'),
  search: require('./source/ic_search.png'),
  user: require('./source/ic_user.png'),
  arrow_down: require('./source/arrow_down.png'),
  check: require('./source/check.png'),
  arrow_left: require('./source/arrow-left.png'),
  go: require('./source/arrow.png'),
  auto_renew: require('./source/autorenew.png'),
  ic_loading_dot: require('./source/ic_loading_dot.png'),
  open_new: require('./source/open_new.png'),
  icon_text: require('./source/icon_text.png'),
  notify: require('./source/ic_notify.png'),
  menu: require('./source/ic_menu.png'),
  home_search: require('./source/ic_home_search.png'),
  point: require('./source/ic_point.png'),
  service: require('./source/ic_service.png'),
  terms: require('./source/ic_terms.png'),
  setting_notify: require('./source/ic_setting_notify.png'),
  security: require('./source/ic_security.png'),
  register: require('./source/ic_register.png'),
  questions: require('./source/ic_questions.png'),
  notify_side: require('./source/ic_notify_side.png'),
  mail: require('./source/ic_mail.png'),
  logout: require('./source/ic_logout.png'),
  home_side: require('./source/ic_home_side.png'),
  block_user: require('./source/ic_block_user.png'),
  content: require('./source/ic_content.png'),
};

export type IconTypes = keyof typeof icons;
