import Config from 'react-native-config';

export const ENVConfig = {
  APP_ENV: Config.APP_ENV,
  API_URL: Config.API_URL,
  API_URL_PRO: Config.API_URL_PRO,
  APP_DISPLAY_NAME: Config.APP_DISPLAY_NAME,
  APP_PLACEHOLDER_NAME: Config.APP_PLACEHOLDER_NAME,
  VERSION_CODE: Config.VERSION_CODE,
  VERSION_NAME: Config.VERSION_NAME,
  BUNDLE_IDENTIFIER: Config.BUNDLE_IDENTIFIER,
  DEFAULT_FALLBACK_LNG_I18n: Config.DEFAULT_FALLBACK_LNG_I18n,
  REGION: Config.REGION,
  USER_POOL_ID: Config.USER_POOL_ID,
  USER_POOL_WEB_CLIENT_ID: Config.USER_POOL_WEB_CLIENT_ID,
  API_PROVINCE: Config.API_PROVINCE,
  API_City: Config.API_City,
  API_Postal_code: Config.API_Postal_code,
};
